services:
  app:
    build: .
    container_name: p3-metalearning
    ports:
      - "9091:9091"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: projects-mysql
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    volumes:
      - profile_images:/app/tomcat/webapps/ROOT/WEB-INF/classes/KDT/profileimages
      - course_images:/app/tomcat/webapps/ROOT/WEB-INF/classes/static/images
      - course_uploads:/app/tomcat/webapps/ROOT/WEB-INF/classes/static/uploads
    networks:
      - p2_network
    restart: unless-stopped

volumes:
  profile_images:
  course_images:
  course_uploads:

networks:
  p2_network:
    external: true
    name: koslearn_default    # EC2에서 `docker network ls`로 실제 이름 확인 후 수정
